language: cpp

matrix:
  include:

    - os: linux
      compiler: gcc
      env: CXX_COMPILER="g++-4.9" CC_COMPILER="gcc-4.9"

      deploy:
        provider: s3
        access_key_id: AKIAJWIQHHHXQOKABKBQ
        secret_access_key:
          secure: hL592Ly39V1Tju069gM57/Pmr5kMgErO33W6+brNQei2mhL8tStA/QZYD/h4I7g01IbS8QxMDAlZ3NPfVc1LRs64fbvJSlvosLade00nhMzarlX257P3oQLCSWeMCZVdQmrpca9XMRT8AOmgxnklu1nEqHNFxQ32Ctk0WtXPOS6PAfTbicwhX1w7T/4NCAtwF5WFgjCSw8KXnuIU/BIeuZiKvnmXKaOar4WNMv22eIBOXosKpCpq8aPmD5K+baryOsqGJNUUyhlDijXq2mbngCqQaXaTxHpFV744E8RugnQAUHos9Y8qP9c0sIFVyw0pt94CL5PbmVbs2MXxIXkrmutSoBrgsX7tu4q+1HlpHNv9/9S+Cldt5Lwe56AJr3U5LW1Ox5w35uwUDUtAXiJXLHHIkhY/ShbKeTsAlBviLXXZvSR+pdBOCz8GVs1iyp5KSfI/ByhNkhwObqP+F5xotn44w7eo2ymjMPFMxiUX5c9L/GrXJO+4jOwgSNhucXl0yfYJsbdhPo8EvskigFwaYcRbPelOYAWM4oB5AbY1RXn8gqx8h3OFWsKFe/Fy1DVJwSJjqSNW9dANEAoyjymV1WPMe8EFNh6aBv7hq5JU0Vd9eXTVyX8re6QppEr/7jFCi8k88xcdQyzvH9F+cXffKyrqP6xK22rXRJO2sngqkN8=
        bucket: forrestthewoods.binaries
        file: fts_remote_console_linux.zip
        upload-dir: fts_remote_console
        acl: public_read
        skip_cleanup: true
        on:
          repo: forrestthewoods/fts_remote_console

    - os: osx
      compiler: clang
      env: CXX_COMPILER="clang++" CC_COMPILER="clang"
      osx_image: xcode8.2

      deploy:
        provider: s3
        access_key_id: AKIAJWIQHHHXQOKABKBQ
        secret_access_key:
          secure: hL592Ly39V1Tju069gM57/Pmr5kMgErO33W6+brNQei2mhL8tStA/QZYD/h4I7g01IbS8QxMDAlZ3NPfVc1LRs64fbvJSlvosLade00nhMzarlX257P3oQLCSWeMCZVdQmrpca9XMRT8AOmgxnklu1nEqHNFxQ32Ctk0WtXPOS6PAfTbicwhX1w7T/4NCAtwF5WFgjCSw8KXnuIU/BIeuZiKvnmXKaOar4WNMv22eIBOXosKpCpq8aPmD5K+baryOsqGJNUUyhlDijXq2mbngCqQaXaTxHpFV744E8RugnQAUHos9Y8qP9c0sIFVyw0pt94CL5PbmVbs2MXxIXkrmutSoBrgsX7tu4q+1HlpHNv9/9S+Cldt5Lwe56AJr3U5LW1Ox5w35uwUDUtAXiJXLHHIkhY/ShbKeTsAlBviLXXZvSR+pdBOCz8GVs1iyp5KSfI/ByhNkhwObqP+F5xotn44w7eo2ymjMPFMxiUX5c9L/GrXJO+4jOwgSNhucXl0yfYJsbdhPo8EvskigFwaYcRbPelOYAWM4oB5AbY1RXn8gqx8h3OFWsKFe/Fy1DVJwSJjqSNW9dANEAoyjymV1WPMe8EFNh6aBv7hq5JU0Vd9eXTVyX8re6QppEr/7jFCi8k88xcdQyzvH9F+cXffKyrqP6xK22rXRJO2sngqkN8=
        bucket: forrestthewoods.binaries
        file: fts_remote_console_macosx.zip
        upload-dir: fts_remote_console
        acl: public_read
        skip_cleanup: true
        on:
          repo: forrestthewoods/fts_remote_console

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - clang++-3.6
    - clang-3.6
    - linux-libc-dev
    - libx11-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxrandr-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - freeglut3-dev

branches:
  only:
    - master

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd projects/gmake_linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd projects/gmake_macosx; fi
  
  - make config=release64 CXX=${CXX_COMPILER} CC=${CC_COMPILER}


before_deploy:
  - mkdir deploy
  - cp -r bin/x64_release/example_game/ deploy
  - cp -r bin/x64_release/fts_remote_console/ deploy
  - cd deploy

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then zip -r fts_remote_console_linux.zip example_game fts_remote_console; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then zip -r fts_remote_console_macosx.zip example_game fts_remote_console.app; fi


notifications:
  email: false


